In [128]:
import pandas as pd

In [129]:
df=pd.read_csv(r"c:\Users\Public\messy_data\studentsmarks.csv")

In [130]:
print(df.loc[(df["maths"] > 5 ) & (df["science"] < 40)])

  student  language  science  maths  history
2   sammy        90     23.0   12.0       32

In [131]:
print(df.loc[(df["maths"] >5 ) | (df["science"] < 40)])

  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10      NaN   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65
6  carrol        50     90.0   45.0       23

In [132]:
print(df.loc[~(df["maths"]>20)])

  student  language  science  maths  history
2   sammy        90     23.0   12.0       32
5    prem        90     45.0    NaN       34

In [133]:
df["maths"]>20

0     True
1     True
2    False
3     True
4     True
5    False
6     True
Name: maths, dtype: bool

In [134]:
~(df["maths"]>20)

0    False
1    False
2     True
3    False
4    False
5     True
6    False
Name: maths, dtype: bool

In [135]:
df.loc[~(df["maths"]>20)]

  student  language  science  maths  history
2   sammy        90     23.0   12.0       32
5    prem        90     45.0    NaN       34

In [136]:
df

  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10      NaN   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0    NaN       34
6  carrol        50     90.0   45.0       23

In [137]:
df.at[0,"maths"]   # here we give

np.float64(34.0)

In [138]:
df.iat[0,2]   # here we give index value of row and columnns

np.float64(56.0)

In [139]:
df[df["maths"].isin([80,90,95])]   # if maths column has these values then it gives the row

  student  language  science  maths  history
3  janice        20      NaN   90.0       45

In [140]:
df[df["science"].between(20,45)]   # here starting and ending value included

  student  language  science  maths  history
2   sammy        90     23.0   12.0       32
5    prem        90     45.0    NaN       34

In [141]:
df.query("maths > 80")

  student  language  science  maths  history
3  janice        20      NaN   90.0       45

In [142]:
df.query("maths > 30 and science > 20")

  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
4   peter        30     56.0   45.0       65
6  carrol        50     90.0   45.0       23

In [143]:
df.nlargest(3, "maths")

  student  language  science  maths  history
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65
6  carrol        50     90.0   45.0       23

In [144]:
df.nsmallest(2, "history")

  student  language  science  maths  history
6  carrol        50     90.0   45.0       23
2   sammy        90     23.0   12.0       32

In [145]:
df["maths"].value_counts()

maths
45.0    2
34.0    1
32.0    1
12.0    1
90.0    1
Name: count, dtype: int64

In [146]:
df["total"] = df["history"] + df["maths"]
df

  student  language  science  maths  history  total
0   kumar        90     56.0   34.0       34   68.0
1   kevin        10      NaN   32.0       67   99.0
2   sammy        90     23.0   12.0       32   44.0
3  janice        20      NaN   90.0       45  135.0
4   peter        30     56.0   45.0       65  110.0
5    prem        90     45.0    NaN       34    NaN
6  carrol        50     90.0   45.0       23   68.0

In [147]:
df.insert(2 , "ai" , [78,45,6,77,8,89,7])
df

  student  language  ai  science  maths  history  total
0   kumar        90  78     56.0   34.0       34   68.0
1   kevin        10  45      NaN   32.0       67   99.0
2   sammy        90   6     23.0   12.0       32   44.0
3  janice        20  77      NaN   90.0       45  135.0
4   peter        30   8     56.0   45.0       65  110.0
5    prem        90  89     45.0    NaN       34    NaN
6  carrol        50   7     90.0   45.0       23   68.0

In [148]:
df.drop("uma",axis=1)

KeyError: "['uma'] not found in axis"

In [ ]:
df

  student  language  ai  science  maths  history  total
0   kumar        90  78     56.0   34.0       34   68.0
1   kevin        10  45      NaN   32.0       67   99.0
2   sammy        90   6     23.0   12.0       32   44.0
3  janice        20  77      NaN   90.0       45  135.0
4   peter        30   8     56.0   45.0       65  110.0
5    prem        90  89     45.0    NaN       34    NaN
6  carrol        50   7     90.0   45.0       23   68.0

In [ ]:
df.assign(attendance="present",score=0)

  student  language  ai  science  maths  history  total attendance  score
0   kumar        90  78     56.0   34.0       34   68.0    present      0
1   kevin        10  45      NaN   32.0       67   99.0    present      0
2   sammy        90   6     23.0   12.0       32   44.0    present      0
3  janice        20  77      NaN   90.0       45  135.0    present      0
4   peter        30   8     56.0   45.0       65  110.0    present      0
5    prem        90  89     45.0    NaN       34    NaN    present      0
6  carrol        50   7     90.0   45.0       23   68.0    present      0

In [ ]:
def grade (marks):
    if marks >= 90:
        return "A"
    elif marks >=70:
        return "B"
    else:
        return "C"
    
df["Grade"] = df["maths"].apply(grade)
df

  student  language  ai  science  maths  history  total Grade
0   kumar        90  78     56.0   34.0       34   68.0     C
1   kevin        10  45      NaN   32.0       67   99.0     C
2   sammy        90   6     23.0   12.0       32   44.0     C
3  janice        20  77      NaN   90.0       45  135.0     A
4   peter        30   8     56.0   45.0       65  110.0     C
5    prem        90  89     45.0    NaN       34    NaN     C
6  carrol        50   7     90.0   45.0       23   68.0     C

In [ ]:
grade_map = {
    90:"Excellent",
    45:"Good",
    30:"Average"
}

df["Performance"] = df["maths"].map(grade_map)
df

  student  language  ai  science  maths  history  total Grade Performance
0   kumar        90  78     56.0   34.0       34   68.0     C         NaN
1   kevin        10  45      NaN   32.0       67   99.0     C         NaN
2   sammy        90   6     23.0   12.0       32   44.0     C         NaN
3  janice        20  77      NaN   90.0       45  135.0     A   Excellent
4   peter        30   8     56.0   45.0       65  110.0     C        Good
5    prem        90  89     45.0    NaN       34    NaN     C         NaN
6  carrol        50   7     90.0   45.0       23   68.0     C        Good

In [ ]:
grade_map = {
    90:"Excellent",
    45:"Good",
    30:"Average"
}

df["Performance"] = df["maths"].map(grade)
df

  student  language  ai  science  maths  history  total Grade Performance
0   kumar        90  78     56.0   34.0       34   68.0     C           C
1   kevin        10  45      NaN   32.0       67   99.0     C           C
2   sammy        90   6     23.0   12.0       32   44.0     C           C
3  janice        20  77      NaN   90.0       45  135.0     A           A
4   peter        30   8     56.0   45.0       65  110.0     C           C
5    prem        90  89     45.0    NaN       34    NaN     C           C
6  carrol        50   7     90.0   45.0       23   68.0     C           C

In [ ]:
import numpy as np

df["status"] = np.where(df["maths"] >= 40, "pass","fail")
df

,student,language,ai,science,maths,history,total,Grade,Performance,status
0,kumar,90,78,56.0,34.0,34,68.0,C,C,fail
1,kevin,10,45,NaN,32.0,67,99.0,C,C,fail
2,sammy,90,6,23.0,12.0,32,44.0,C,C,fail
3,janice,20,77,NaN,90.0,45,135.0,A,A,pass
4,peter,30,8,56.0,45.0,65,110.0,C,C,pass
5,prem,90,89,45.0,NaN,34,NaN,C,C,fail
6,carrol,50,7,90.0,45.0,23,68.0,C,C,pass

In [ ]:
df=df.drop(columns="Performance")
df

  student  language  ai  science  maths  history  total Grade status
0   kumar        90  78     56.0   34.0       34   68.0     C   fail
1   kevin        10  45      NaN   32.0       67   99.0     C   fail
2   sammy        90   6     23.0   12.0       32   44.0     C   fail
3  janice        20  77      NaN   90.0       45  135.0     A   pass
4   peter        30   8     56.0   45.0       65  110.0     C   pass
5    prem        90  89     45.0    NaN       34    NaN     C   fail
6  carrol        50   7     90.0   45.0       23   68.0     C   pass

In [ ]:
df=df.drop(2,axis=0)
df

  student  language  ai  science  maths  history  total Grade status
0   kumar        90  78     56.0   34.0       34   68.0     C   fail
1   kevin        10  45      NaN   32.0       67   99.0     C   fail
3  janice        20  77      NaN   90.0       45  135.0     A   pass
4   peter        30   8     56.0   45.0       65  110.0     C   pass
5    prem        90  89     45.0    NaN       34    NaN     C   fail
6  carrol        50   7     90.0   45.0       23   68.0     C   pass

In [ ]:
df=df.drop("ai",axis=1)
df

  student  language  science  maths  history  total Grade status
0   kumar        90     56.0   34.0       34   68.0     C   fail
1   kevin        10      NaN   32.0       67   99.0     C   fail
3  janice        20      NaN   90.0       45  135.0     A   pass
4   peter        30     56.0   45.0       65  110.0     C   pass
5    prem        90     45.0    NaN       34    NaN     C   fail
6  carrol        50     90.0   45.0       23   68.0     C   pass

In [ ]:
removed_column = df.pop("total")

print(removed_column)
df

0     68.0
1     99.0
3    135.0
4    110.0
5      NaN
6     68.0
Name: total, dtype: float64

  student  language  science  maths  history Grade status
0   kumar        90     56.0   34.0       34     C   fail
1   kevin        10      NaN   32.0       67     C   fail
3  janice        20      NaN   90.0       45     A   pass
4   peter        30     56.0   45.0       65     C   pass
5    prem        90     45.0    NaN       34     C   fail
6  carrol        50     90.0   45.0       23     C   pass

In [ ]:
df=df.rename(columns={"maths":"mathematics"})
df

  student  language  science  mathematics  history Grade status
0   kumar        90     56.0         34.0       34     C   fail
1   kevin        10      NaN         32.0       67     C   fail
3  janice        20      NaN         90.0       45     A   pass
4   peter        30     56.0         45.0       65     C   pass
5    prem        90     45.0          NaN       34     C   fail
6  carrol        50     90.0         45.0       23     C   pass

In [ ]:
df=df.rename(columns={
    "science":"sci",
    "history":"hist"
})

df

  student  language   sci  mathematics  hist Grade status
0   kumar        90  56.0         34.0    34     C   fail
1   kevin        10   NaN         32.0    67     C   fail
3  janice        20   NaN         90.0    45     A   pass
4   peter        30  56.0         45.0    65     C   pass
5    prem        90  45.0          NaN    34     C   fail
6  carrol        50  90.0         45.0    23     C   pass

In [149]:
df.sort_values(by="history").reset_index().drop("index",axis=1)

  student  language  ai  science  maths  history  total
0  carrol        50   7     90.0   45.0       23   68.0
1   sammy        90   6     23.0   12.0       32   44.0
2    prem        90  89     45.0    NaN       34    NaN
3   kumar        90  78     56.0   34.0       34   68.0
4  janice        20  77      NaN   90.0       45  135.0
5   peter        30   8     56.0   45.0       65  110.0
6   kevin        10  45      NaN   32.0       67   99.0

In [150]:
df.sort_values(
    by="science",
    na_position="last"
)

  student  language  ai  science  maths  history  total
2   sammy        90   6     23.0   12.0       32   44.0
5    prem        90  89     45.0    NaN       34    NaN
0   kumar        90  78     56.0   34.0       34   68.0
4   peter        30   8     56.0   45.0       65  110.0
6  carrol        50   7     90.0   45.0       23   68.0
1   kevin        10  45      NaN   32.0       67   99.0
3  janice        20  77      NaN   90.0       45  135.0