In [155]:
import pandas as pd

## series

In [156]:
s=pd.Series([12,35,46,67])
print(s)

0    12
1    35
2    46
3    67
dtype: int64

In [157]:
u=pd.Series([54,22,66],index=['a','b','c'])
print(u)

a    54
b    22
c    66
dtype: int64

In [158]:
print(u['b'])

22

In [159]:
g=pd.Series([34,67,11,5],index=['s','r','d','q'])
print(g)

s    34
r    67
d    11
q     5
dtype: int64

In [160]:
print(g['d'])

11

## dataframe

In [161]:
data={'name':['uma','vedik','vijay'],
      'age':[44,11,57],
      'city':['jaipur','delhi','indore']}
df=pd.DataFrame(data)
print(df)

    name  age    city
0    uma   44  jaipur
1  vedik   11   delhi
2  vijay   57  indore

In [162]:
print(df.shape)

(3, 3)

In [163]:
print(df.columns)

Index(['name', 'age', 'city'], dtype='str')

In [164]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [165]:
print(df.dtypes) # shows the datatype of each column

name      str
age     int64
city      str
dtype: object

In [166]:
print(df.info)

<bound method DataFrame.info of     name  age    city
0    uma   44  jaipur
1  vedik   11   delhi
2  vijay   57  indore>

In [167]:
print(df.describe())

             age
count   3.000000
mean   37.333333
std    23.713569
min    11.000000
25%    27.500000
50%    44.000000
75%    50.500000
max    57.000000

In [168]:
print(df.head(2)) #it print first two column

    name  age    city
0    uma   44  jaipur
1  vedik   11   delhi

In [169]:
print(df.tail(2)) #it print last two column

    name  age    city
1  vedik   11   delhi
2  vijay   57  indore

In [170]:
data={'product':['pen','book','bag'],
      'price':[10,50,100],
      'stock':[100,20,5]}
df=pd.DataFrame(data)
df

  product  price  stock
0     pen     10    100
1    book     50     20
2     bag    100      5

In [171]:
print(df.shape)

(3, 3)

In [172]:
print(df.columns)

Index(['product', 'price', 'stock'], dtype='str')

In [173]:
print(df.head(2))

  product  price  stock
0     pen     10    100
1    book     50     20

In [174]:
df=pd.read_csv(r"C:\Users\umara\Downloads\student.csv")

In [175]:
df.head()

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [176]:
df.tail()

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [177]:
pd.read_csv(r'C:\Users\umara\Downloads\student.csv',nrows=10)

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [178]:
df["Age"]=[10,20,30,40,50]
df

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [179]:
df["city"]=['jaipur','indore','delhi','pune','ujjain']
df

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [180]:
pd.read_csv(r'C:\Users\umara\Downloads\student.csv',usecols=['name'])
df

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [181]:
df.to_csv(r'C:\Users\umara\Downloads\student.csv',index=False)
df

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

practice

In [182]:
u={"name":['uma','vedik','vijay'],
   "marks":[44,11,57],}
df=pd.DataFrame(u)
print(df.head())
print(df.shape)
print(df.describe())

    name  marks
0    uma     44
1  vedik     11
2  vijay     57
(3, 2)
           marks
count   3.000000
mean   37.333333
std    23.713569
min    11.000000
25%    27.500000
50%    44.000000
75%    50.500000
max    57.000000

In [183]:
v={"name":['uma','vedik','vijay','komal','ajay','riya'],
   "marks":[64,98,77,67,89,90],
   "grade":['A','A+','B','B+','A','A+']}
df=pd.DataFrame(v)
df
print(df.head())
print(df.shape)
print(df.describe())
print(df.info())
print(df.columns)

    name  marks grade
0    uma     64     A
1  vedik     98    A+
2  vijay     77     B
3  komal     67    B+
4   ajay     89     A
(6, 3)
           marks
count   6.000000
mean   80.833333
std    13.673575
min    64.000000
25%    69.500000
50%    83.000000
75%    89.750000
max    98.000000
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   marks   6 non-null      int64
 2   grade   6 non-null      str
dtypes: int64(1), str(2)
memory usage: 276.0 bytes
None
Index(['name', 'marks', 'grade'], dtype='str')

In [184]:
df=pd.read_csv(r'C:\Users\umara\Downloads\student.csv')
df

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

#### selecting columns

In [185]:
df["name"]

0    Aarav
1     Diya
2    Kabir
3    Meera
4    Rohan
Name: name, dtype: str

In [186]:
df[['name','Age']]

    name  Age
0  Aarav   10
1   Diya   20
2  Kabir   30
3  Meera   40
4  Rohan   50

### selecting columns using slicing

In [187]:
df[0:2]

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore

In [188]:
df[1:5]

    name  marks grade  Age    city
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

### loc(local based)

In [189]:
df=pd.read_csv(r'C:\Users\umara\Downloads\student.csv')
df

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [190]:
df.loc[1,'Age'] #it will give the value of age column in 1st row

np.int64(20)

In [191]:
df.loc[3,'name'] #it will give the value of name column in 3rd row

'Meera'

In [192]:
df.loc[4] #it will give the value of all columns in 4th row

name      Rohan
marks        81
grade         B
Age          50
city     ujjain
Name: 4, dtype: object

In [193]:
df.loc[1:3,['Age','city']] #it will give the value of age and city column in 1st to 3rd row

   Age    city
1   20  indore
2   30   delhi
3   40    pune

In [194]:
df.loc[4,'name']

'Rohan'

In [195]:
df.loc[0:4,["marks"]]

   marks
0     88
1     92
2     76
3     95
4     81

### iloc(index based) 
##### it uses integer position

In [196]:
df.iloc[0:4,2] #it will give the value of marks column in 0 to 4 row

0    B
1    A
2    C
3    A
Name: grade, dtype: str

In [197]:
df.iloc[1,4] #it will give the value of city column in 1st row

'indore'

In [198]:
df.iloc[0:3,0:4] #it will give the value of all columns in 0 to 3 row,here 0:3 means 0 to 2 row and 0:4 means 0 to 3 column

    name  marks grade  Age
0  Aarav     88     B   10
1   Diya     92     A   20
2  Kabir     76     C   30

##### difference b/w loc and iloc

In [199]:
df.loc[0:3] #it include 0 to 3 row and all columns

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi
3  Meera     95     A   40    pune

In [200]:
df.iloc[0:3] # it include 0 to 2 row and all columns

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
2  Kabir     76     C   30   delhi

### filtering
##### this is where analysis begins

In [201]:
df[df["Age"]>30] #it will give the value of all columns where age is greater than 30

    name  marks grade  Age    city
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

In [202]:
df[df["grade"]=='A'] #it will give the value of all columns where grade is A

    name  marks grade  Age    city
1   Diya     92     A   20  indore
3  Meera     95     A   40    pune

In [203]:
df[df["marks"]<90] #it will give the value of all columns where marks is less than 90

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
2  Kabir     76     C   30   delhi
4  Rohan     81     B   50  ujjain

In [204]:
df[(df["Age"]>30) & (df["grade"]=='A')] #it will give the value of all columns where age is greater than 30 and grade is A

    name  marks grade  Age  city
3  Meera     95     A   40  pune

In [205]:
df[(df["marks"]>80) & (df["grade"]=='A')] #it will give the value of all columns where marks is greater than 80 and grade is A

    name  marks grade  Age    city
1   Diya     92     A   20  indore
3  Meera     95     A   40    pune

In [206]:
df[(df["marks"]>80) | (df["grade"]=='A')] # it will give the value of all columns where marks is greater than 80 or grade is A

    name  marks grade  Age    city
0  Aarav     88     B   10  jaipur
1   Diya     92     A   20  indore
3  Meera     95     A   40    pune
4  Rohan     81     B   50  ujjain

### data cleaning

In [207]:
data={'name':['uma','vedik','vijay','komal','ajay','riya'],
        'marks':[64,98,None,67,89,90],
        'grade':[None,'A+','B','B+',None,'A+']}   
df=pd.DataFrame(data)
df

    name  marks grade
0    uma   64.0   NaN
1  vedik   98.0    A+
2  vijay    NaN     B
3  komal   67.0    B+
4   ajay   89.0   NaN
5   riya   90.0    A+

In [208]:
df.isnull() # it will give the boolean value true for null value and false for non null value

    name  marks  grade
0  False  False   True
1  False  False  False
2  False   True  False
3  False  False  False
4  False  False   True
5  False  False  False

In [209]:
df.isnull().sum() # it will give the count of null value in each column

name     0
marks    1
grade    2
dtype: int64

#### drop  missing value

In [210]:
df.dropna() # it will drop the row which contain null value

    name  marks grade
1  vedik   98.0    A+
3  komal   67.0    B+
5   riya   90.0    A+

In [238]:
df.dropna(subset=["marks"]) # it will drop the row which contain null value in marks column but it will not drop the row which contain null value in grade column

    name  marks    grade    city
0    uma   64.0  Unknown  jaipur
1  vedik   98.0       A+   delhi
2  vijay   81.6        B  indore
3  komal   67.0       B+    pune
4   ajay   89.0  Unknown  ujjain
5   riya   90.0       A+  bhopal

### fill missing value

In [239]:
import numpy as np
df["marks"]=df["marks"].fillna(np.mean(df["marks"])) # it will fill the null value in marks column with mean value of marks column
df

    name  marks    grade    city
0    uma   64.0  Unknown  jaipur
1  vedik   98.0       A+   delhi
2  vijay   81.6        B  indore
3  komal   67.0       B+    pune
4   ajay   89.0  Unknown  ujjain
5   riya   90.0       A+  bhopal

In [224]:
df['city']=['jaipur','delhi','indore','pune','ujjain','bhopal']
df

    name  marks grade    city
0    uma   64.0   NaN  jaipur
1  vedik   98.0    A+   delhi
2  vijay   81.6     B  indore
3  komal   67.0    B+    pune
4   ajay   89.0   NaN  ujjain
5   riya   90.0    A+  bhopal

In [236]:
df.fillna({'marks': 0, 'grade': 'Unknown'}, inplace=True) # it will fill the null value with 0 in marks column and unknown in grade column
df

    name  marks    grade    city
0    uma   64.0  Unknown  jaipur
1  vedik   98.0       A+   delhi
2  vijay   81.6        B  indore
3  komal   67.0       B+    pune
4   ajay   89.0  Unknown  ujjain
5   riya   90.0       A+  bhopal

In [237]:
df['name']=df['name'].fillna('Unknown') # it will fill the null value in name column with unknown
df

    name  marks    grade    city
0    uma   64.0  Unknown  jaipur
1  vedik   98.0       A+   delhi
2  vijay   81.6        B  indore
3  komal   67.0       B+    pune
4   ajay   89.0  Unknown  ujjain
5   riya   90.0       A+  bhopal

In [241]:
df.duplicated() # it will give the boolean value true for duplicate value and false for non duplicate value

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool