In [1]:
import pandas as pd

In [3]:
s=pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [4]:
d={
    "name":["uma","duggu"],
    "marks":[99,22]
}

df=pd.DataFrame(d)
df

    name  marks
0    uma     99
1  duggu     22

In [7]:
a=pd.Series([100,43,"laddu",89] , index=["a","b",1,"d"])
a

a      100
b       43
1    laddu
d       89
dtype: object

In [10]:
u={
    "math":78,
    "eng":34,
    "hindi":99
    
}

df=pd.DataFrame(u, index=[1,2,3])
df

   math  eng  hindi
1    78   34     99
2    78   34     99
3    78   34     99

In [12]:
print(u["eng"])

34

In [44]:
o=pd.Series([10,20,708,90,20])
print(o[0])

10

In [38]:
o.sum()

np.int64(828)

In [45]:
o.mode()

0    20
dtype: int64

In [42]:
o.median()

np.float64(55.0)

In [41]:
o.mean()

np.float64(207.0)

In [40]:
o.max()

np.int64(708)

In [39]:
o.min()

np.int64(10)

In [37]:
print(o/10)

0     1.0
1     2.0
2    70.8
3     9.0
dtype: float64

In [35]:
print(o>40)

0    False
1    False
2     True
3     True
dtype: bool

In [36]:
print(o<20)

0     True
1    False
2    False
3    False
dtype: bool

In [30]:
print(o.loc[3])

90

In [33]:
print(o.iloc[3])

90

In [31]:
print(o.loc[2:3])

2    708
3     90
dtype: int64

In [34]:
print(o.iloc[2:3])  # it  cant include ending value

2    708
dtype: int64

In [ ]:
print(o.loc[-2])

In [19]:
print(o.iloc[-2])

708

In [15]:
w=pd.Series([10,20,708,90], index=["a","b","c","d"])
w

a     10
b     20
c    708
d     90
dtype: int64

In [16]:
print(w.loc["a"])

10

In [ ]:
print(w.iloc["b"])

In [ ]:
d=[["uma",22,99],["duggu",21,95]]
df=pd.DataFrame(d)